package mail.sandbox.dashboard.server.acceptance

import java.io.ByteArrayOutputStream
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.LinkOption
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import java.nio.file.attribute.PosixFilePermission
import java.security.MessageDigest
import java.time.Duration
import java.time.Instant
import java.util.Base64
import java.util.Comparator
import java.util.UUID
import java.util.concurrent.atomic.AtomicReference
import kotlin.io.path.name
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import mail.sandbox.dashboard.contract.AccountInfo
import mail.sandbox.dashboard.contract.Provider

internal data class SingleStackCommandResult(
    val exitCode: Int,
    val stdout: String,
    val stderr: String,
)

internal fun interface SingleStackCommandRunner {
    fun run(argv: List<String>): SingleStackCommandResult
}

internal data class AcceptanceRunIdentity(val prefix: String) {
    init {
        require(PREFIX.matches(prefix)) {
            "Acceptance prefix must be unique and generated by the live runner"
        }
    }

    fun accountAddress(provider: Provider): String =
        "$prefix-${provider.name.lowercase()}@local.test"

    fun folderName(suffix: String): String {
        require(SUFFIX.matches(suffix)) { "Acceptance resource suffix is invalid" }
        return "$prefix-$suffix"
    }

    fun ownsAddress(address: String): Boolean =
        Provider.entries.any { accountAddress(it) == address }

    fun ownsName(name: String): Boolean =
        name == prefix || name.startsWith("$prefix-")

    companion object {
        private val PREFIX = Regex(
            "^dashboard-acceptance-[0-9]{10,}-[0-9a-f]{8,32}$",
        )
        private val SUFFIX = Regex("^[a-z0-9][a-z0-9-]{0,31}$")

        fun generate(): AcceptanceRunIdentity = AcceptanceRunIdentity(
            "dashboard-acceptance-${Instant.now().epochSecond}-" +
                UUID.randomUUID().toString().replace("-", "").take(12),
        )
    }
}

@Serializable
internal data class ProviderIdentitySnapshot(
    val provider: Provider,
    val address: String,
    val providerAccountId: String? = null,
)

@Serializable
internal data class TreeEntrySnapshot(
    val relativePath: String,
    val kind: String,
    val size: Long = 0,
    val sha256: String? = null,
)

@Serializable
internal data class MaildirRootSnapshot(
    val accountRoot: String,
    val entries: List<TreeEntrySnapshot>,
)

@Serializable
internal data class MigrationEvidenceSnapshot(
    val currentReceiptBase64: String,
    val sourceReceiptBase64: String,
    val retainedSnapshotPath: String,
)

@Serializable
internal data class ComposeServiceIdentity(
    val service: String,
    val containerId: String,
)

@Serializable
internal data class RootComposeIdentity(
    val project: String,
    val repositoryRoot: String,
    val composeFile: String,
    val services: List<ComposeServiceIdentity>,
)

@Serializable
internal data class SingleStackPreservationSnapshot(
    val schema: String = SCHEMA,
    val repositoryRoot: String,
    val runPrefix: String,
    val usersInitiallyExisted: Boolean,
    val expectedUsersBase64: String,
    val dovecotRecords: List<String>,
    val maildirRoots: List<MaildirRootSnapshot>,
    val providerAccounts: List<ProviderIdentitySnapshot>,
    val dashboardCatalogInitiallyExisted: Boolean,
    val dashboardCatalogBase64: String? = null,
    val migration: MigrationEvidenceSnapshot,
    val compose: RootComposeIdentity,
) {
    init {
        require(schema == SCHEMA) { "Acceptance preservation snapshot schema is unsupported" }
    }

    override fun toString(): String =
        "SingleStackPreservationSnapshot(schema=$schema, runPrefix=$runPrefix, redacted=true)"

    companion object {
        const val SCHEMA = "mail-sandbox.single-stack-preservation.v1"
    }
}

internal class SingleStackAcceptanceEnvironment private constructor(
    val repositoryRoot: Path,
    val run: AcceptanceRunIdentity,
    private val snapshotPath: Path,
    private val commandRunner: SingleStackCommandRunner,
) {
    fun requireGeneratedAddress(address: String): String = address.also {
        require(run.ownsAddress(address)) {
            "Cleanup target does not belong to this acceptance run"
        }
    }

    fun requireGeneratedAccount(account: AccountInfo): AccountInfo = account.also {
        require(account.address == run.accountAddress(account.provider)) {
            "Account cleanup identity does not belong to this acceptance run"
        }
        when (account.provider) {
            Provider.DOVECOT -> require(account.providerAccountId == null) {
                "Generated Dovecot cleanup must not carry a provider Account ID"
            }
            Provider.STALWART -> require(!account.providerAccountId.isNullOrBlank()) {
                "Generated Stalwart cleanup requires its exact provider Account ID"
            }
        }
    }

    fun requireGeneratedFolder(name: String): String = name.also {
        require(run.ownsName(name)) {
            "Folder cleanup target does not belong to this acceptance run"
        }
    }

    fun purgeGeneratedDovecotMaildir(address: String) {
        val generated = requireGeneratedAddress(address)
        require(generated == run.accountAddress(Provider.DOVECOT)) {
            "Only the generated Dovecot account Maildir may be purged"
        }
        val vmail = repositoryRoot.resolve("vmail").normalize()
        val target = vmail.resolve(generated).normalize()
        require(target.parent == vmail && target.fileName.toString() == generated) {
            "Dovecot Maildir cleanup target is invalid"
        }
        if (Files.notExists(target, LinkOption.NOFOLLOW_LINKS)) return
        requirePlainDirectory(target, "generated Dovecot Maildir")
        val paths = Files.walk(target).use { stream ->
            stream.limit(MAXIMUM_TREE_ENTRIES.toLong() + 1).toList()
        }
        require(paths.size <= MAXIMUM_TREE_ENTRIES) {
            "Generated Dovecot Maildir exceeds the cleanup bound"
        }
        paths.forEach { path ->
            require(!Files.isSymbolicLink(path)) {
                "Generated Dovecot Maildir contains a symbolic link"
            }
        }
        paths.sortedWith(Comparator.reverseOrder()).forEach(Files::delete)
    }

    fun removeGeneratedCatalogIfInitiallyAbsent(snapshot: SingleStackPreservationSnapshot) {
        check(snapshot.repositoryRoot == repositoryRoot.toString() && snapshot.runPrefix == run.prefix) {
            "Refusing catalog cleanup for a foreign preservation snapshot"
        }
        if (snapshot.dashboardCatalogInitiallyExisted) return
        val catalog = dashboardCatalogPath()
        if (Files.notExists(catalog, LinkOption.NOFOLLOW_LINKS)) return
        val bytes = readBoundedRegular(
            catalog,
            MAXIMUM_CATALOG_BYTES,
            "dashboard account catalog",
        )
        val safeToRemove = runCatching {
            val document = JSON.parseToJsonElement(bytes.toString(StandardCharsets.UTF_8)).jsonObject
            document.keys == setOf("version", "accounts") &&
                document.getValue("version").jsonPrimitive.content == "2" &&
                document.getValue("accounts").jsonArray.isEmpty()
        }.getOrDefault(false)
        bytes.fill(0)
        check(safeToRemove) {
            "Refusing to remove a dashboard catalog that contains non-generated state"
        }
        Files.delete(catalog)
    }

    fun capturePreservation(
        accounts: List<AccountInfo>,
        commandRunner: SingleStackCommandRunner = this.commandRunner,
    ): SingleStackPreservationSnapshot {
        val users = repositoryRoot.resolve("config/users")
        val defaults = repositoryRoot.resolve("config/users.defaults")
        val existed = Files.exists(users, LinkOption.NOFOLLOW_LINKS)
        val expectedUsers = if (existed) {
            readBoundedRegular(users, MAXIMUM_USERS_BYTES, "config/users")
        } else {
            val recovered = readBoundedRegular(
                defaults,
                MAXIMUM_USERS_BYTES,
                "config/users.defaults",
            )
            check(parseDovecotRecords(recovered).size == EXPECTED_DEFAULT_ACCOUNT_COUNT) {
                "The recovery users fixture must contain exactly nine accounts"
            }
            recovered
        }
        val catalog = dashboardCatalogPath()
        val catalogExisted = Files.exists(catalog, LinkOption.NOFOLLOW_LINKS)
        val catalogBytes = if (catalogExisted) {
            readBoundedRegular(catalog, MAXIMUM_CATALOG_BYTES, "dashboard account catalog")
        } else {
            null
        }
        return SingleStackPreservationSnapshot(
            repositoryRoot = repositoryRoot.toString(),
            runPrefix = run.prefix,
            usersInitiallyExisted = existed,
            expectedUsersBase64 = expectedUsers.base64(),
            dovecotRecords = parseDovecotRecords(expectedUsers),
            maildirRoots = captureMaildirRoots(),
            providerAccounts = accountIdentities(accounts),
            dashboardCatalogInitiallyExisted = catalogExisted,
            dashboardCatalogBase64 = catalogBytes?.base64(),
            migration = captureMigrationEvidence(commandRunner),
            compose = captureComposeIdentity(commandRunner),
        )
    }

    fun assertPreserved(
        expected: SingleStackPreservationSnapshot,
        accounts: List<AccountInfo>,
        commandRunner: SingleStackCommandRunner = this.commandRunner,
    ) {
        check(expected.repositoryRoot == repositoryRoot.toString()) {
            "Preservation snapshot belongs to another repository"
        }
        check(expected.runPrefix == run.prefix) {
            "Preservation snapshot belongs to another acceptance run"
        }
        val users = repositoryRoot.resolve("config/users")
        check(Files.exists(users, LinkOption.NOFOLLOW_LINKS)) {
            if (expected.usersInitiallyExisted) {
                "The pre-existing Dovecot users authority was removed"
            } else {
                "Missing Dovecot users authority was not bootstrapped"
            }
        }
        val currentUsers = readBoundedRegular(users, MAXIMUM_USERS_BYTES, "config/users")
        check(currentUsers.base64() == expected.expectedUsersBase64) {
            "The Dovecot users authority changed outside the generated insertion/removal cycle"
        }
        check(parseDovecotRecords(currentUsers) == expected.dovecotRecords) {
            "The pre-existing Dovecot records changed"
        }
        check(captureMaildirRoots() == expected.maildirRoots) {
            "A pre-existing Dovecot Maildir changed or a generated Maildir remains"
        }
        check(accountIdentities(accounts) == expected.providerAccounts) {
            "The pre-existing provider account inventory changed"
        }
        val catalog = dashboardCatalogPath()
        val catalogExists = Files.exists(catalog, LinkOption.NOFOLLOW_LINKS)
        check(catalogExists == expected.dashboardCatalogInitiallyExisted) {
            "The dashboard account catalog presence changed"
        }
        if (catalogExists) {
            check(
                readBoundedRegular(
                    catalog,
                    MAXIMUM_CATALOG_BYTES,
                    "dashboard account catalog",
                ).base64() == expected.dashboardCatalogBase64,
            ) {
                "The pre-existing dashboard account catalog changed"
            }
        }
        check(captureMigrationEvidence(commandRunner) == expected.migration) {
            "The validated Stalwart migration evidence changed"
        }
        check(captureComposeIdentity(commandRunner) == expected.compose) {
            "The root Compose service/project identity changed"
        }
    }

    fun writeSnapshot(snapshot: SingleStackPreservationSnapshot) {
        check(snapshot.repositoryRoot == repositoryRoot.toString()) {
            "Refusing to persist a foreign preservation snapshot"
        }
        val parent = requireNotNull(snapshotPath.parent)
        require(parent == acceptanceRunDirectory()) {
            "Acceptance snapshot path is outside its exact run directory"
        }
        Files.createDirectories(parent)
        setOwnerOnlyDirectory(parent)
        check(!Files.isSymbolicLink(snapshotPath)) {
            "Acceptance snapshot must not be a symbolic link"
        }
        val encoded = (JSON.encodeToString(snapshot) + "\n").toByteArray()
        check(encoded.size <= MAXIMUM_SNAPSHOT_BYTES) {
            "Acceptance snapshot exceeds its size bound"
        }
        val temporary = parent.resolve(".${snapshotPath.fileName}.${UUID.randomUUID()}.tmp")
        try {
            Files.write(temporary, encoded)
            setOwnerOnlyFile(temporary)
            try {
                Files.move(
                    temporary,
                    snapshotPath,
                    StandardCopyOption.ATOMIC_MOVE,
                    StandardCopyOption.REPLACE_EXISTING,
                )
            } catch (_: java.nio.file.AtomicMoveNotSupportedException) {
                Files.move(temporary, snapshotPath, StandardCopyOption.REPLACE_EXISTING)
            }
            setOwnerOnlyFile(snapshotPath)
        } finally {
            Files.deleteIfExists(temporary)
            encoded.fill(0)
        }
    }

    fun readSnapshot(): SingleStackPreservationSnapshot {
        val encoded = readBoundedRegular(
            snapshotPath,
            MAXIMUM_SNAPSHOT_BYTES,
            "acceptance preservation snapshot",
        )
        return try {
            JSON.decodeFromString(encoded.toString(StandardCharsets.UTF_8))
        } finally {
            encoded.fill(0)
        }
    }

    private fun acceptanceRunDirectory(): Path = repositoryRoot.resolve(
        "debug-dashboard/.runtime/acceptance/${run.prefix}",
    ).normalize()

    private fun dashboardCatalogPath(): Path = repositoryRoot.resolve(
        "debug-dashboard/.runtime/dashboard/accounts.json",
    ).normalize()

    private fun captureMaildirRoots(): List<MaildirRootSnapshot> {
        val vmail = repositoryRoot.resolve("vmail")
        if (Files.notExists(vmail, LinkOption.NOFOLLOW_LINKS)) return emptyList()
        requirePlainDirectory(vmail, "vmail root")
        val roots = Files.list(vmail).use { stream -> stream.sorted().toList() }
        check(roots.size <= MAXIMUM_MAILDIR_ROOTS) { "Dovecot Maildir root count exceeds its bound" }
        var totalEntries = 0
        var totalBytes = 0L
        return roots.map { root ->
            requirePlainDirectory(root, "Dovecot account Maildir root")
            val entries = captureTree(root)
            totalEntries += entries.size
            check(totalEntries <= MAXIMUM_TREE_ENTRIES) {
                "Dovecot Maildir snapshot exceeds its global entry bound"
            }
            totalBytes += entries.sumOf(TreeEntrySnapshot::size)
            check(totalBytes <= MAXIMUM_TREE_BYTES) {
                "Dovecot Maildir snapshot exceeds its global byte bound"
            }
            MaildirRootSnapshot(
                accountRoot = root.fileName.toString(),
                entries = entries,
            )
        }
    }

    private fun captureTree(root: Path): List<TreeEntrySnapshot> {
        var totalBytes = 0L
        val entries = Files.walk(root).use { stream ->
            stream.skip(1).limit(MAXIMUM_TREE_ENTRIES.toLong() + 1).sorted().map { path ->
                check(!Files.isSymbolicLink(path)) { "Maildir snapshot refuses symbolic links" }
                val relative = root.relativize(path).joinToString("/")
                when {
                    Files.isDirectory(path, LinkOption.NOFOLLOW_LINKS) ->
                        TreeEntrySnapshot(relative, "directory")
                    Files.isRegularFile(path, LinkOption.NOFOLLOW_LINKS) -> {
                        val size = Files.size(path)
                        totalBytes += size
                        check(totalBytes <= MAXIMUM_TREE_BYTES) {
                            "Dovecot Maildir snapshot exceeds its byte bound"
                        }
                        TreeEntrySnapshot(relative, "file", size, sha256(path))
                    }
                    else -> error("Maildir snapshot refuses a special filesystem entry")
                }
            }.toList()
        }
        check(entries.size <= MAXIMUM_TREE_ENTRIES) {
            "Dovecot Maildir snapshot exceeds its entry bound"
        }
        return entries
    }

    private fun captureMigrationEvidence(
        runner: SingleStackCommandRunner,
    ): MigrationEvidenceSnapshot {
        val classifier = runner.requireSuccess(
            listOf(
                "python3",
                repositoryRoot.resolve("scripts/stalwart_runtime_state.py").toString(),
                "classify",
                "--repository",
                repositoryRoot.toString(),
            ),
            "Stalwart current-runtime receipt validation",
        )
        check(classifier.stdout.trim() == "current") {
            "Stalwart runtime must be validated as current"
        }
        val sourceReceipt = repositoryRoot.resolve(
            "debug-dashboard/.runtime/stalwart-migration/latest-source.json",
        )
        runner.requireSuccess(
            listOf(
                "python3",
                repositoryRoot.resolve("scripts/capture_stalwart_v015.py").toString(),
                "verify",
                "--receipt",
                sourceReceipt.toString(),
            ),
            "retained Stalwart migration snapshot validation",
        )
        val currentBytes = readBoundedRegular(
            repositoryRoot.resolve("debug-dashboard/.runtime/stalwart/current.json"),
            MAXIMUM_RECEIPT_BYTES,
            "Stalwart current receipt",
        )
        val sourceBytes = readBoundedRegular(
            sourceReceipt,
            MAXIMUM_RECEIPT_BYTES,
            "Stalwart source receipt",
        )
        val retained = try {
            JSON.parseToJsonElement(sourceBytes.toString(StandardCharsets.UTF_8))
                .jsonObject.getValue("payload").jsonObject
                .getValue("backup").jsonObject
                .getValue("root").jsonPrimitive.content
                .let(Path::of)
                .toAbsolutePath()
                .normalize()
        } catch (failure: Exception) {
            throw IllegalStateException("Validated Stalwart source receipt is malformed", failure)
        }
        val approvedBackups = repositoryRoot.resolve(
            "captures/debug-dashboard/stalwart-v015/backups",
        ).normalize()
        check(retained.parent == approvedBackups && retained.name.startsWith("stalwart-v015-")) {
            "Retained Stalwart snapshot path is outside the approved backup root"
        }
        requirePlainDirectory(retained, "retained Stalwart snapshot")
        return MigrationEvidenceSnapshot(
            currentReceiptBase64 = currentBytes.base64(),
            sourceReceiptBase64 = sourceBytes.base64(),
            retainedSnapshotPath = retained.toString(),
        )
    }

    private fun captureComposeIdentity(runner: SingleStackCommandRunner): RootComposeIdentity {
        val composeFile = repositoryRoot.resolve("docker-compose.yml")
        val result = runner.requireSuccess(
            listOf(
                "docker",
                "compose",
                "-f",
                composeFile.toString(),
                "ps",
                "-a",
                "--format",
                "json",
            ),
            "root Compose identity capture",
        )
        val objects = parseComposeObjects(result.stdout)
        val projects = objects.map { it.requiredString("Project") }.distinct()
        check(projects.size == 1 && projects.single().isNotBlank()) {
            "Root Compose services do not share one project identity"
        }
        val services = objects.map { objectValue ->
            ComposeServiceIdentity(
                service = objectValue.requiredString("Service"),
                containerId = objectValue.requiredString("ID"),
            )
        }.sortedBy(ComposeServiceIdentity::service)
        check(services.map(ComposeServiceIdentity::service).toSet() == REQUIRED_SERVICES) {
            "Root Compose does not expose exactly the required mail services"
        }
        check(services.map(ComposeServiceIdentity::service).distinct().size == services.size) {
            "Root Compose contains duplicate required services"
        }
        return RootComposeIdentity(
            project = projects.single(),
            repositoryRoot = repositoryRoot.toString(),
            composeFile = composeFile.toString(),
            services = services,
        )
    }

    companion object {
        const val LIVE_TESTS_KEY = "DASHBOARD_SINGLE_STACK_LIVE_TESTS"
        const val RUN_PREFIX_KEY = "DASHBOARD_SINGLE_STACK_RUN_PREFIX"
        const val SNAPSHOT_KEY = "DASHBOARD_SINGLE_STACK_SNAPSHOT"

        val EXACT_ENDPOINTS: Map<String, String> = linkedMapOf(
            "DASHBOARD_SINGLE_STACK_DOVECOT_IMAP_ENDPOINT" to "127.0.0.1:1143",
            "DASHBOARD_SINGLE_STACK_DOVECOT_POP3_ENDPOINT" to "127.0.0.1:1110",
            "DASHBOARD_SINGLE_STACK_POSTFIX_DELIVERY_ENDPOINT" to "127.0.0.1:1025",
            "DASHBOARD_SINGLE_STACK_POSTFIX_SUBMISSION_ENDPOINT" to "127.0.0.1:1587",
            "DASHBOARD_SINGLE_STACK_OAUTH2_ENDPOINT" to "http://127.0.0.1:8080",
            "DASHBOARD_SINGLE_STACK_STALWART_JMAP_ENDPOINT" to "http://127.0.0.1:8443",
            "DASHBOARD_SINGLE_STACK_STALWART_SMTP_ENDPOINT" to "127.0.0.1:8587",
        )

        fun load(
            environment: Map<String, String> = System.getenv(),
            repositoryRoot: Path = discoverRepositoryRoot(),
            commandRunner: SingleStackCommandRunner = JvmSingleStackCommandRunner,
        ): SingleStackAcceptanceEnvironment {
            require(environment[LIVE_TESTS_KEY] == "1") {
                "$LIVE_TESTS_KEY=1 is required for the selected live acceptance class"
            }
            EXACT_ENDPOINTS.forEach { (key, exact) ->
                require(environment[key] == exact) {
                    "$key must select the exact root loopback endpoint $exact"
                }
            }
            val root = repositoryRoot.toAbsolutePath().normalize()
            require(root == repositoryRoot && !Files.isSymbolicLink(root)) {
                "Acceptance repository root must be normalized, absolute, and not a symlink"
            }
            requirePlainDirectory(root.resolve(".git"), "primary Git directory")
            requirePrimaryCheckout(root, commandRunner)
            val run = AcceptanceRunIdentity(
                environment[RUN_PREFIX_KEY]
                    ?: throw IllegalArgumentException("$RUN_PREFIX_KEY is required"),
            )
            val expectedSnapshot = root.resolve(
                "debug-dashboard/.runtime/acceptance/${run.prefix}/baseline.json",
            ).normalize()
            val selectedSnapshot = environment[SNAPSHOT_KEY]
                ?.let(Path::of)
                ?.toAbsolutePath()
                ?.normalize()
                ?: throw IllegalArgumentException("$SNAPSHOT_KEY is required")
            require(selectedSnapshot == expectedSnapshot) {
                "$SNAPSHOT_KEY must select this run's exact ignored preservation path"
            }
            return SingleStackAcceptanceEnvironment(root, run, selectedSnapshot, commandRunner)
        }

        private fun requirePrimaryCheckout(root: Path, runner: SingleStackCommandRunner) {
            val top = runner.requireSuccess(
                listOf("git", "-C", root.toString(), "rev-parse", "--show-toplevel"),
                "primary checkout top-level verification",
            ).stdout.trim().let(Path::of).toAbsolutePath().normalize()
            val commonText = runner.requireSuccess(
                listOf("git", "-C", root.toString(), "rev-parse", "--git-common-dir"),
                "primary checkout common-directory verification",
            ).stdout.trim()
            val commonCandidate = Path.of(commonText)
            val common = (if (commonCandidate.isAbsolute) commonCandidate else root.resolve(commonCandidate))
                .toAbsolutePath()
                .normalize()
            require(top == root && common == root.resolve(".git")) {
                "Live acceptance must run from the primary checkout"
            }
        }

        private fun discoverRepositoryRoot(): Path {
            var candidate = Path.of(System.getProperty("user.dir")).toAbsolutePath().normalize()
            repeat(5) {
                if (
                    Files.isRegularFile(candidate.resolve("docker-compose.yml")) &&
                    Files.isDirectory(candidate.resolve("debug-dashboard"))
                ) return candidate
                candidate = candidate.parent
                    ?: error("Could not locate the mail-sandbox primary checkout")
            }
            error("Could not locate the mail-sandbox primary checkout")
        }
    }
}

private object JvmSingleStackCommandRunner : SingleStackCommandRunner {
    override fun run(argv: List<String>): SingleStackCommandResult {
        require(argv.isNotEmpty()) { "Acceptance command must not be empty" }
        val process = ProcessBuilder(argv)
            .redirectErrorStream(true)
            .start()
        val output = AtomicReference<ByteArray>()
        val failure = AtomicReference<Throwable?>()
        val reader = Thread({
            try {
                process.inputStream.use { input ->
                    val sink = ByteArrayOutputStream()
                    val buffer = ByteArray(8 * 1024)
                    var total = 0
                    while (true) {
                        val read = input.read(buffer)
                        if (read < 0) break
                        total += read
                        check(total <= MAXIMUM_COMMAND_OUTPUT_BYTES) {
                            "Acceptance command output exceeded its bound"
                        }
                        sink.write(buffer, 0, read)
                    }
                    output.set(sink.toByteArray())
                }
            } catch (cause: Throwable) {
                failure.set(cause)
            }
        }, "single-stack-acceptance-command-reader").apply { isDaemon = true }
        reader.start()
        if (!process.waitFor(COMMAND_TIMEOUT.toMillis(), java.util.concurrent.TimeUnit.MILLISECONDS)) {
            process.destroyForcibly()
            reader.join(1_000)
            error("Acceptance command timed out")
        }
        reader.join(1_000)
        check(!reader.isAlive) { "Acceptance command reader did not finish" }
        failure.get()?.let { throw IllegalStateException("Acceptance command output failed", it) }
        val text = String(output.get() ?: ByteArray(0), StandardCharsets.UTF_8)
        return SingleStackCommandResult(process.exitValue(), text, "")
    }
}

private fun SingleStackCommandRunner.requireSuccess(
    argv: List<String>,
    label: String,
): SingleStackCommandResult = run(argv).also { result ->
    check(result.exitCode == 0) {
        "$label failed: " + (result.stderr.ifBlank { result.stdout }).trim().take(240)
    }
}

private fun parseComposeObjects(text: String): List<JsonObject> {
    val trimmed = text.trim()
    check(trimmed.isNotEmpty()) { "Root Compose identity output is empty" }
    val parsed = runCatching { JSON.parseToJsonElement(trimmed) }.getOrNull()
    if (parsed is JsonArray) return parsed.jsonArray.map(JsonElement::jsonObject)
    return trimmed.lineSequence().filter(String::isNotBlank).map { line ->
        JSON.parseToJsonElement(line).jsonObject
    }.toList()
}

private fun JsonObject.requiredString(name: String): String =
    get(name)?.jsonPrimitive?.content?.takeIf(String::isNotBlank)
        ?: error("Root Compose identity has no $name")

private fun accountIdentities(accounts: List<AccountInfo>): List<ProviderIdentitySnapshot> =
    accounts.map { account ->
        when (account.provider) {
            Provider.DOVECOT -> check(account.providerAccountId == null) {
                "Dovecot inventory unexpectedly contains a provider Account ID"
            }
            Provider.STALWART -> check(!account.providerAccountId.isNullOrBlank()) {
                "Stalwart inventory is missing a provider Account ID"
            }
        }
        ProviderIdentitySnapshot(
            provider = account.provider,
            address = account.address,
            providerAccountId = account.providerAccountId,
        )
    }.sortedWith(compareBy(ProviderIdentitySnapshot::provider, ProviderIdentitySnapshot::address))

private fun parseDovecotRecords(content: ByteArray): List<String> {
    val text = StandardCharsets.UTF_8.newDecoder().decode(java.nio.ByteBuffer.wrap(content)).toString()
    if (text.isEmpty()) return emptyList()
    check(text.endsWith('\n')) { "Dovecot users authority is not canonically terminated" }
    val addresses = text.dropLast(1).split('\n').map { line ->
        val fields = line.split(':')
        check(fields.size == 8 && fields.drop(2).all(String::isEmpty)) {
            "Dovecot users authority is not in canonical eight-field form"
        }
        check(fields[0].isNotBlank() && fields[1].startsWith("{PLAIN}")) {
            "Dovecot users authority contains an unsupported record"
        }
        fields[0]
    }
    check(addresses.distinct().size == addresses.size) {
        "Dovecot users authority contains duplicate records"
    }
    return addresses
}

private fun readBoundedRegular(path: Path, maximum: Int, label: String): ByteArray {
    check(!Files.isSymbolicLink(path) && Files.isRegularFile(path, LinkOption.NOFOLLOW_LINKS)) {
        "$label must be a plain regular file"
    }
    val size = Files.size(path)
    check(size in 0..maximum.toLong()) { "$label exceeds its size bound" }
    val bytes = Files.readAllBytes(path)
    check(bytes.size <= maximum) { "$label changed beyond its size bound while reading" }
    return bytes
}

private fun requirePlainDirectory(path: Path, label: String) {
    require(!Files.isSymbolicLink(path) && Files.isDirectory(path, LinkOption.NOFOLLOW_LINKS)) {
        "$label must be a plain directory"
    }
}

private fun sha256(path: Path): String {
    val digest = MessageDigest.getInstance("SHA-256")
    Files.newInputStream(path).use { input ->
        val buffer = ByteArray(16 * 1024)
        while (true) {
            val read = input.read(buffer)
            if (read < 0) break
            digest.update(buffer, 0, read)
        }
        buffer.fill(0)
    }
    return digest.digest().joinToString("") { byte -> "%02x".format(byte) }
}

private fun ByteArray.base64(): String = Base64.getEncoder().encodeToString(this)

private fun setOwnerOnlyDirectory(path: Path) {
    runCatching {
        Files.setPosixFilePermissions(
            path,
            setOf(
                PosixFilePermission.OWNER_READ,
                PosixFilePermission.OWNER_WRITE,
                PosixFilePermission.OWNER_EXECUTE,
            ),
        )
    }
}

private fun setOwnerOnlyFile(path: Path) {
    runCatching {
        Files.setPosixFilePermissions(
            path,
            setOf(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE),
        )
    }
}

private val JSON = Json {
    encodeDefaults = true
    ignoreUnknownKeys = false
}
private val COMMAND_TIMEOUT = Duration.ofSeconds(30)
private val REQUIRED_SERVICES = setOf("dovecot", "postfix", "oauth2-mock", "stalwart")
private const val EXPECTED_DEFAULT_ACCOUNT_COUNT = 9
private const val MAXIMUM_USERS_BYTES = 1024 * 1024
private const val MAXIMUM_CATALOG_BYTES = 4 * 1024 * 1024
private const val MAXIMUM_RECEIPT_BYTES = 8 * 1024 * 1024
private const val MAXIMUM_SNAPSHOT_BYTES = 16 * 1024 * 1024
private const val MAXIMUM_COMMAND_OUTPUT_BYTES = 2 * 1024 * 1024
private const val MAXIMUM_MAILDIR_ROOTS = 10_000
private const val MAXIMUM_TREE_ENTRIES = 100_000
private const val MAXIMUM_TREE_BYTES = 8L * 1024 * 1024 * 1024
