# config/10-auth.conf
auth_mechanisms = plain login oauthbearer xoauth2
auth_allow_cleartext = yes   # ok for LOCAL dev + TLS

# OAuth2 introspection settings (used by passdb oauth2 below)
oauth2_introspection_mode = post
oauth2_introspection_url = http://oauth2-mock:8080/introspect
oauth2_username_attribute = username
oauth2_active_attribute = active
oauth2_active_value = true

passdb passwd-file {
  passwd_file_path = /etc/dovecot/runtime/users
}

passdb oauth2 {
  mechanisms_filter = xoauth2 oauthbearer
}

userdb passwd-file {
  passwd_file_path = /etc/dovecot/runtime/users
  fields {
    uid:default = 1000
    gid:default = 1000
    home:default = /srv/vmail/%{user}
  }
}
