package mail.sandbox.dashboard.server.local

import java.time.Instant
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter
import kotlin.math.absoluteValue
import kotlin.random.Random
import mail.sandbox.dashboard.contract.GenerateMessageRequest
import mail.sandbox.dashboard.contract.MessageSourceType

internal data class GeneratedMessage(val rawEml: String)

internal class MessageGenerator {
    fun generate(request: GenerateMessageRequest): List<GeneratedMessage> {
        val target = requireAddress(request.targetAccount, "target account")
        val sender = requireAddress(request.fromAddress ?: DEFAULT_SENDER, "sender")
        require(request.count in 1..MAX_COUNT) { "Message count must be between 1 and $MAX_COUNT" }
        request.subject?.let { requireHeader(it, "subject") }

        return when (request.sourceType) {
            MessageSourceType.EML -> {
                val raw = request.content?.takeIf(String::isNotBlank)
                    ?: throw IllegalArgumentException("EML content is required")
                require(raw.length <= MAX_MESSAGE_CHARS) { "EML content is too large" }
                List(request.count) { GeneratedMessage(raw) }
            }

            MessageSourceType.TEXT -> {
                val body = request.content
                    ?: throw IllegalArgumentException("Text content is required")
                require(body.length <= MAX_MESSAGE_CHARS) { "Text content is too large" }
                List(request.count) { index ->
                    GeneratedMessage(
                        composeMessage(
                            target = target,
                            sender = sender,
                            subject = request.subject ?: DEFAULT_SUBJECT,
                            body = body,
                            messageId = "text-${System.nanoTime()}-$index@local.test",
                            instant = Instant.now(),
                            extraHeaders = emptyList(),
                        ),
                    )
                }
            }

            MessageSourceType.RANDOM -> generateRandom(request, target, sender)
        }
    }

    private fun generateRandom(
        request: GenerateMessageRequest,
        target: String,
        sender: String,
    ): List<GeneratedMessage> {
        val seed = request.seed ?: System.nanoTime()
        val random = Random(seed)
        return List(request.count) { index ->
            val subject = request.subject ?: buildString {
                append(SUBJECT_PREFIXES[random.nextInt(SUBJECT_PREFIXES.size)])
                append(' ')
                append(SUBJECT_TOPICS[random.nextInt(SUBJECT_TOPICS.size)])
                append(" #")
                append(index + 1)
            }
            val body = buildString {
                appendLine(BODY_OPENERS[random.nextInt(BODY_OPENERS.size)])
                appendLine()
                repeat(2 + random.nextInt(3)) {
                    appendLine(BODY_DETAILS[random.nextInt(BODY_DETAILS.size)])
                }
                appendLine()
                append("Generated by the local Mail Flight Recorder.")
            }
            val instant = Instant.ofEpochSecond(
                RANDOM_EPOCH_SECONDS + (seed % RANDOM_DATE_WINDOW).absoluteValue + index,
            )
            GeneratedMessage(
                composeMessage(
                    target = target,
                    sender = sender,
                    subject = subject,
                    body = body,
                    messageId = "random-$seed-$index@local.test",
                    instant = instant,
                    extraHeaders = listOf(
                        "X-Dashboard-Seed: $seed",
                        "X-Dashboard-Sequence: ${index + 1}",
                    ),
                ),
            )
        }
    }

    private fun composeMessage(
        target: String,
        sender: String,
        subject: String,
        body: String,
        messageId: String,
        instant: Instant,
        extraHeaders: List<String>,
    ): String {
        requireHeader(subject, "subject")
        val normalizedBody = body.replace("\r\n", "\n").replace('\r', '\n')
            .split('\n')
            .joinToString("\r\n")
        return buildString {
            append("From: ").append(sender).append("\r\n")
            append("To: ").append(target).append("\r\n")
            append("Subject: ").append(subject).append("\r\n")
            append("Date: ").append(DATE_FORMAT.format(instant.atZone(ZoneOffset.UTC))).append("\r\n")
            append("Message-ID: <").append(messageId).append(">\r\n")
            append("MIME-Version: 1.0\r\n")
            append("Content-Type: text/plain; charset=UTF-8\r\n")
            append("Content-Transfer-Encoding: 8bit\r\n")
            extraHeaders.forEach { append(it).append("\r\n") }
            append("\r\n")
            append(normalizedBody)
            append("\r\n")
        }
    }

    private fun requireAddress(value: String, label: String): String {
        require(ADDRESS.matches(value)) { "$label must be a canonical local.test address" }
        return value
    }

    private fun requireHeader(value: String, label: String) {
        require(value.isNotBlank() && value.length <= 998 && '\r' !in value && '\n' !in value) {
            "$label is invalid"
        }
    }

    private companion object {
        const val MAX_COUNT = 100
        const val MAX_MESSAGE_CHARS = 5 * 1024 * 1024
        const val DEFAULT_SENDER = "debugger@local.test"
        const val DEFAULT_SUBJECT = "Dashboard test message"
        const val RANDOM_EPOCH_SECONDS = 1_700_000_000L
        const val RANDOM_DATE_WINDOW = 31_536_000L
        val ADDRESS = Regex("[a-z0-9][a-z0-9._+%-]{0,63}@local\\.test")
        val DATE_FORMAT: DateTimeFormatter = DateTimeFormatter.RFC_1123_DATE_TIME
        val SUBJECT_PREFIXES = listOf("Re:", "Fwd:", "Update:", "Question:", "Incident:")
        val SUBJECT_TOPICS = listOf(
            "sync state",
            "mailbox migration",
            "message rendering",
            "provider behavior",
            "client reproduction",
        )
        val BODY_OPENERS = listOf(
            "Here is a generated message for the current reproduction.",
            "This fixture exercises a local provider interaction.",
            "Please use this message while inspecting the client behavior.",
        )
        val BODY_DETAILS = listOf(
            "The message intentionally contains multiple lines.",
            "Its identifiers are deterministic when a seed is supplied.",
            "It is safe to move, flag, copy, or delete this fixture.",
            "Both provider and client logs can be correlated with this delivery.",
        )
    }
}
